---
modes:
  default:
    Description: "Perform a scan using default options"
    PingCount: 0
    MaxPort: 0
  fast:
    Description: "Perform a quick scan"
    PingCount: 1
    MaxPort: 1023
  thorough:
    Description: "Perform a thorough scan"
    PingCount: 4
    MaxPort: 10000
  invasive:
    Description: "Perform an aggressive scan"
    PingCount: 0
    MaxPort: 10000